# Generated by Django 5.0.4 on 2024-04-27 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('premium', 'premium'), ('normal', 'normal'), ('vintage', 'vintage')], max_length=100)),
                ('Type', models.CharField(choices=[('sedan', 'sedan'), ('hatchback', 'hatchback'), ('suv', 'suv'), ('coupe', 'coupe'), ('pickup', 'pickup'), ('convertable', 'convertable'), ('van', 'van'), ('wagon', 'wagon')], max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric')], max_length=100)),
                ('transmission', models.CharField(choices=[('Manuel', 'Manuel'), ('Automatic', 'Automatic')], max_length=50)),
                ('image_black', models.ImageField(blank=True, null=True, upload_to='car_images_black')),
                ('image_white', models.ImageField(blank=True, null=True, upload_to='car_images_white')),
                ('image_red', models.ImageField(blank=True, null=True, upload_to='car_images_red')),
                ('image_blue', models.ImageField(blank=True, null=True, upload_to='car_images_blue')),
                ('image_green', models.ImageField(blank=True, null=True, upload_to='car_images_green')),
                ('milage', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(default='Per Day', max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('trivandram', 'trivandram'), ('kollam', 'kollam'), ('alappuzha', 'alappuzha'), ('pathanamthitta', 'pathanamthitta'), ('kottayam', 'kottayam'), ('idukki', 'idukki'), ('ernakulam', 'eranakulam'), ('thrissur', 'thrissur'), ('palakkad', 'palakkad'), ('malappuram', 'malappuram'), ('kozhikode', 'kozhikode'), ('wayanad', 'wayanad'), ('kannur', 'kannur'), ('kasargod', 'kasargod')], default='kozhikode', max_length=100)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('final', models.DateField()),
                ('duration', models.IntegerField(null=True)),
                ('total', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_bookings_name', to='wwapp.carcategory')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_bookings_price', to='wwapp.carcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_image')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('single', 'single'), ('marrid', 'married')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
