# Generated by Django 5.0.4 on 2024-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='image_black',
            field=models.ImageField(blank=True, null=True, upload_to='car_images_1'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='image_blue',
            field=models.ImageField(blank=True, null=True, upload_to='car_images_4'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='image_green',
            field=models.ImageField(blank=True, null=True, upload_to='car_images_5'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='image_red',
            field=models.ImageField(blank=True, null=True, upload_to='car_images_3'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='image_white',
            field=models.ImageField(blank=True, null=True, upload_to='car_images_2'),
        ),
    ]
