# Generated by Django 5.0.4 on 2024-04-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_alter_carcategory_image_black_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='final',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='start',
        ),
    ]
