# Generated by Django 5.0.4 on 2024-05-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0003_remove_carbooking_final_remove_carbooking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsmodel',
            name='area',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
