# Generated by Django 5.0.4 on 2024-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0004_locationsmodel_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='category',
            field=models.CharField(choices=[('premium', 'premium'), ('vintage', 'vintage')], max_length=100),
        ),
    ]
