# Generated by Django 5.0.4 on 2024-05-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0005_alter_carcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='place',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='total',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='user',
        ),
    ]
