# Generated by Django 5.0.4 on 2024-05-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0006_remove_carbooking_contact_remove_carbooking_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
