# Generated by Django 5.0.4 on 2024-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0008_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
